export {default as Home} from './Home/Home'
export {default as Meetings} from './Meetings/Meetings'
export {default as AboutUs} from './AboutUs/AboutUs'
export {default as ContactUs} from './ContactUs/ContactUs'

export {default as RoomsPage} from './Rooms/RoomsPage'
export {default as Delux} from './Rooms/Delux'
export {default as DoubleDelux} from './Rooms/DoubleDelux'
export {default as ExecutiveSuite} from './Rooms/ExecutiveSuite'
export {default as StandardRoom} from './Rooms/StandardRoom'
export {default as Suite} from './Rooms/Suite'
export {default as GalleryPage} from './GalleryPage/GalleryPage'